### PR TITLE
File splitting

### PR DESCRIPTION
**Pull request by csb048**
Made changes to CmakeLists.txt so that is uses the correct directory for libnetcdff.a depending on the user's OS.

Summa-OpenWQ now runs with snow.  added an additional subroutine in allocspace.f90 to allocate space specificity for progStruct_timestep_start. Modified how the progstuct is being copied by including different cases for different variable types.  And changed he how some of the arrays are being indexed by changing how many times it iterates though loops and by adding offsets.

### CODE REVIEW

**Comment by KyleKlenk** [comment]
Hey Chris,

Thanks for creating the fix and performing the tests to ensure the old behavior still works.

There are a few things that need to be cleaned up before accepting this merge.

The first is the CMakeLists.txt file is part of the openWQ repository separate from this one. Those changes will need to be submitted as a pull request there.

Second, can you change the location of the subroutine, `allocGlobal_porgStruct` it should not be in `allocspace.f90` as this file is specific to SUMMA and should remain unchanged. Instead, the subroutine should go in a new file in the `build/source/openwq` directory.

Also when passing the number of snow layers to the new subroutine, it should be encapsulated within a variable and not just the number 5.

**Comment by csb048** [comment]
Hey Kyle,

I implemented the changed you mentioned.  the subroutine `allocGlobal_progstuct()` is now housed in  `build/source/openwq/summa_openWQ_allocspace.f90`.  Also there is a new variable `max_snow_layers` that's used when calling the new subroutine. 

Since a new file was made I also made a change to `CmakeLists.txt` so its included in the compilation.  You can see that in another pull request I'll be making shortly on the openwq repo.

**Comment by KyleKlenk** [comment]
These changes look good, thanks for updating them. I have also tested these and they are working as expected. I am ready to close this, and I am just waiting to give Diogo a chance to review them if he would like.

**Comment by csb048** [comment]
the `last_hru_flag` established in `Summa_OpenWQ.f90:` in `run_time_start_go()` is manipulated improperly when passed though into `openwq_rime_time_start()` in `OpenWQ_hydrolink.cpp` resulting in false positives.  Added alternative conditional that fixes this.    Now when looking at the openWQ output there are non-zero values, however the dimensions are not correct.  Each time step should have `n` dimensions for the number of GRUs being ran, they always have one dimension as if its the results of a single GRU run.

**Comment by csb048** [comment]
the `last_hru_flag` established in `Summa_OpenWQ.f90:` in `run_time_start_go()` is manipulated improperly when passed though into `openwq_rime_time_start()` in `OpenWQ_hydrolink.cpp` resulting in false positives.  Added alternative conditional that fixes this.    Now when looking at the openWQ output there are non-zero values, however the dimensions are not correct.  Each time step should have `n` dimensions for the number of GRUs being ran, they always have one dimension as if its the results of a single GRU run.

**Comment by csb048** [comment]
In `hydrolink.cpp` an attribute (`numDimentions`) part of the `OpenWQ_output` class is set to be equal the number of HRUs being computed.  This is so the value can be passed though latter to another scope.

This is related to another commit made on the openwq repository, https://github.com/ue-hydro/openwq/commit/de491ddfb6bb464e15bff649c421e1117bec26b1

**Comment by csb048** [comment]
Added a try-catch sequence that will check if the environment variable 'master_json' exists. The actual set_OpenWQ_masterjson() function checks if the path is valid already.

**Pull request merged**
